### ISSUE TITLE
It's not possible to use FoBo with embedded jetty 9 (servlet-api 2.5 takes precedence)

### ISSUE THREAD

**Issue by yukoff** [karma4u101/FoBo#64]
Hi! Seems currently it's impossible to use FoBo with embedded jetty 9 (tried v9.3.x) - in the end jetty's org.eclipse.jetty.servlet.DefaultServlet will extend HttpServlet from the servlet-api v2.5 (which is a dependency for TwBs-Bootstrap3), casing exceptions during runtime, eg.
```
09:28:43.302 [qtp265119009-15] WARN  org.eclipse.jetty.server.HttpChannel - //localhost:8080/
java.lang.NoSuchMethodError: javax.servlet.http.HttpServletRequest.getDispatcherType()Ljavax/servlet/DispatcherType;
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:202)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Unknown Source)
```

Seems the major problem here i that in such configuration jetty-webapp and javax.servlet should be resolved at compile time:
```
libraryDependencies ++= {
...
    "net.liftmodules"	%%	"fobo_3.0"			% "1.5"			% "compile",
...
    "org.eclipse.jetty"	%	"jetty-webapp"		% jettyVersion	% "compile,container,test",
...
    "javax.servlet"		%	"javax.servlet-api"	% "3.1.0"		% "provided",
...
}
```

**Comment by karma4u101** [comment]
Ah yes thanks, you are absolutely right. In this case there should not even bee a dependency on the servlet api so i will remove it. I am currently working on some module refactoring for v1.6  
see In Progress https://waffle.io/karma4u101/FoBo case #56 related to PR #61 
I could publish some FoBo 1.6-SNAPSHOTs in a moment (that will contain the fix) if you wish to try it out. 1.6 snapshots should be fairly stable. I will let you know when the snapshots is available. 

Thank you very much for bringing this to my attention and sorry for the inconvenience. 
best regards Peter Petersson

**Comment by yukoff** [comment]
Thanks for your feedback, @karma4u101! As for now 1.6-SNAPSHOT would be fine, thank you.

**Comment by yukoff** [comment]
BTW description for PR #61 has a lot of sad typos - dose vs. does ;)

**Comment by karma4u101** [comment]
New snapshots has been published take a look and tell me if it resolves the problem. 
It turned out that some tests needed the servlet spec, I updated to 3.1.0 with "provided" set.
Thanks for the heads up on typos in the PR I will look in to it, my native language is Swedish so things like that tend to slip by ;)
